### ISSUE TITLE
显示版本文件已损坏怎么办

### ISSUE THREAD

**Issue by Wadewfsssss** [Mr-xn/hackbar2.1.3#1]

**Comment by Mr-xn** [comment]
请你提供你的Firefox浏览器版本信息，此插件只适用于Firefox浏览器。
我这测试没有问题，你按照步骤操作一遍，可以录制成GIF或者是短视频，给个链接，我给你看看。

**Comment by Wadewfsssss** [comment]
谢谢，我换了个低版本的火狐就好了
