### ISSUE TITLE
输入遇见问题

### ISSUE THREAD

**Issue by K1ruo** [Mr-xn/hackbar2.1.3#4]
加载安装完成后发现在hackbar中的输入框内无法输入 单引号和反斜杠 16进制输入有点麻烦，请问有遇见一样问题的吗，有什么好的解决方法么

**Comment by Mr-xn** [comment]
我刚在Firefox 68测试没问题得，是可以使用单引号和反斜杠

**Comment by K1ruo** [comment]
嗯，目测是新版火狐的不兼容，我试一试低版本的，多谢

**Comment by Mr-xn** [comment]
建议使用火狐esr通道版本 稳定安全
